spring:
  application:
    name: accenture
  datasource:
    url: jdbc:mysql://localhost:3306/franchise_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: franchise_user
    password: franchise_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: INFO
    com.test.franchise: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
